"""
System Metrics - Tracks business performance and AI operations.
Exposes data for Prometheus monitoring.
"""

from prometheus_client import Counter, Histogram, Gauge

# --- Operational Metrics ---
TASKS_EXECUTED = Counter(
    "king_ai_tasks_executed_total", 
    "Total number of tasks executed", 
    ["agent", "status"]
)

TASK_DURATION = Histogram(
    "king_ai_task_duration_seconds", 
    "Duration of task execution in seconds", 
    ["agent"]
)

# --- Financial Metrics ---
REVENUE_GENERATED = Counter(
    "king_ai_revenue_total", 
    "Total revenue generated by the empire", 
    ["business_unit"]
)

EXPENSES_INCURRED = Counter(
    "king_ai_expenses_total", 
    "Total expenses incurred by the empire", 
    ["business_unit", "type"]
)

# --- Empire Status ---
ACTIVE_BUSINESSES = Gauge(
    "king_ai_active_businesses", 
    "Current number of active business units"
)

PENDING_APPROVALS = Gauge(
    "king_ai_pending_approvals", 
    "Number of tasks waiting for human approval"
)

# --- Evolution Metrics ---
EVOLUTIONS_PROPOSED = Counter(
    "king_ai_evolutions_total", 
    "Total number of self-modification proposals", 
    ["type", "status"]
)
